FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set env to production
ENV ENV=production
ENV DATA_DIR=/app/data

# Create data directory just in case it's used locally inside the container
RUN mkdir -p /app/data

CMD ["python", "src/main.py"]
